### PR TITLE
Fix database server version

### PR DESCRIPTION
**Pull request by ausi**
This could fix the issue I think.

### CODE REVIEW

**Comment by joseluisq** [comment]
Great, I will give it a second try.

**Comment by joseluisq** [comment]
Bingo! It works now.



Thanks for the workaround. I think should be mentioned on contao/contao#1696.

**Comment by ausi** [comment]
I will try to check why the version detection does not work as expected here. Is there a command to access a shell of the php container? (My docker knowledge is limited ☺️)

**Comment by joseluisq** [comment]
> Is there a command to access a shell of the php container? (My docker knowledge is limited ☺️)

Yes, just do a `docker exec -it ID_OF_CONTAINER sh` from a new terminal.

You can find the container ID typing something like:

```
docker ps | grep "php-fpm"
```

If you are using Docker for Mac should be more easy via the GUI.

**Pull request merged**
